name: "Build Document"

on:
    push:
        branches:
            - "master"
    release:
        types: [published]

jobs:
    converttopdf:
        permissions:
            contents: read
            pages: write
            id-token: write
        name: Build PDF Document
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3

            - name: Select Front Page
              run: |
                  find ./chapters -type f -name '00_*.md' -print0 |
                  xargs -0 cat |
                  sed -e '$s|$|\n\n|' > frontpage.md

            - name: Convert Frontpage Markdown To PDF
              uses: baileyjm02/markdown-to-pdf@v1
              with:
                  input_dir: frontpage.md
                  output_dir: pdfs
                  images_dir: assets/images
                  # for example <img src="./images/file-name.png">
                  image_import: ../assets/images
                  # Default is true, can set to false to only get PDF files
                  build_html: false
                  theme: ./assets/style.css
                  extend_default_theme: true

            - name: Fix permissions
              run: |
                  chmod -c -R +rX "pdfs/" | while read line; do
                    echo "::warning title=Invalid file permissions automatically fixed::$line"
                  done

            - name: Create testing HTML file
              run: |
                  mkdir site
                  cp pdfs/* site/
                  touch site/index.html
                  echo "<a href="/markdown-pdf-pages-template/frontpage.pdf">PDF</a>" >> site/index.html

            - name: Upload Pages artifact
              uses: actions/upload-pages-artifact@v2
              with:
                  path: "site"

            - name: Deploy to GitHub Pages
              uses: actions/deploy-pages@v2
